#pragma once

#include "config_common.h"

#define VENDOR_ID  0x0C45
#define PRODUCT_ID 0x768A
#define DEVICE_VER 0x0001

#define MANUFACTURER Newmen C87
#define PRODUCT      Newmen C87
#define DESCRIPTION  Newmen C87
#define FORCE_NKRO

#define WAIT_FOR_USB
#define USB_MAX_POWER_CONSUMPTION 500

#define MATRIX_ROWS 6
#define MATRIX_COLS 19

#define DIODE_DIRECTION ROW2COL
#define MATRIX_COL_PINS { A8, A9, A10, A11, A12, A13, A14, A15, D0, D1, D2, D4, D5,D8, A2, A1, A3, A4, A5}
#define MATRIX_ROW_PINS { B0, B1, B2,  B3,  B4,  B5 }

/* LED matrix */
#define LED_MATRIX_ROWS         MATRIX_ROWS
#define LED_MATRIX_ROW_CHANNELS 1
#define LED_MATRIX_ROWS_HW      (LED_MATRIX_ROWS * LED_MATRIX_ROW_CHANNELS)
#define LED_MATRIX_ROW_PINS     { C10,C9,C8,C7,C6 }
#define LED_MATRIX_COLS         MATRIX_COLS
#define LED_MATRIX_COL_PINS     MATRIX_COL_PINS
#define DRIVER_LED_TOTAL        132

/* Dexter's PWM hack */
#define ACTIVATE_PWM_CHAN_8 //A8
#define ACTIVATE_PWM_CHAN_9 //A9
#define ACTIVATE_PWM_CHAN_10 //A10
#define ACTIVATE_PWM_CHAN_11 //A11
#define ACTIVATE_PWM_CHAN_12 //A12
#define ACTIVATE_PWM_CHAN_13 //A13
#define ACTIVATE_PWM_CHAN_14 //A14
#define ACTIVATE_PWM_CHAN_15 //A15
#define ACTIVATE_PWM_CHAN_16 //D0
#define ACTIVATE_PWM_CHAN_17 //D1
#define ACTIVATE_PWM_CHAN_18 //D2
#define ACTIVATE_PWM_CHAN_19 //D3
#define ACTIVATE_PWM_CHAN_22 //D4
#define ACTIVATE_PWM_CHAN_21 //D5
#define ACTIVATE_PWM_CHAN_2 //A2
#define ACTIVATE_PWM_CHAN_1 //A1
#define ACTIVATE_PWM_CHAN_3 //A3
#define ACTIVATE_PWM_CHAN_0 //A0
#define ACTIVATE_PWM_CHAN_4 //A4
#define ACTIVATE_PWM_CHAN_5 //A5
#define ACTIVATE_PWM_CHAN_6 //A6
#define ACTIVATE_PWM_CHAN_7 //A7


/* Debounce reduces chatter (unintended double-presses) - set 0 if debouncing is not needed */
#define DEBOUNCE 5

/* LED Status indicators */
#define LED_CAPS_LOCK_PIN   C1
#define LED_SCROLL_LOCK_PIN C2
#define LED_PIN_ON_STATE    1

/* Enable led matrix effects */
#define ENABLE_LED_MATRIX_ALPHAS_MODS
#define ENABLE_LED_MATRIX_BREATHING
#define ENABLE_LED_MATRIX_BAND
#define ENABLE_LED_MATRIX_BAND_PINWHEEL
#define ENABLE_LED_MATRIX_BAND_SPIRAL
#define ENABLE_LED_MATRIX_CYCLE_LEFT_RIGHT
#define ENABLE_LED_MATRIX_CYCLE_UP_DOWN
#define ENABLE_LED_MATRIX_CYCLE_OUT_IN
#define ENABLE_LED_MATRIX_DUAL_BEACON
#define ENABLE_LED_MATRIX_WAVE_LEFT_RIGHT
#define ENABLE_LED_MATRIX_WAVE_UP_DOWN

// #define LAYER_STATE_8BIT
#define DYNAMIC_KEYMAP_LAYER_COUNT 4
#define DYNAMIC_KEYMAP_EEPROM_MAX_ADDR 1200


